name: Deploy to local cluster
on:
  workflow_call:
    inputs:
      sha:
        description: 'Commit SHA to deploy'
        required: true
        type: string
  workflow_dispatch:

jobs:
  deploy:
    runs-on: home-arc-runners
    container:
      image: bitnami/kubectl@sha256:f737259db1fb8d90b18bcacd6233291ce22c31ac452ca71dc7aad48e90f85ac1

    steps:
      - name: Patch deployment with new image
        run: |
          SHA="${{ inputs.sha || github.sha }}"
          SHORT_SHA="${SHA:0:7}"
          kubectl patch deployment dice-app-deployment --namespace www --patch-file=/dev/stdin <<-EOF
          { "spec": { "template": { "spec": { "containers": [ { "name": "dice-app", "image": "$REGISTRY_URL/${{ github.repository }}:${SHORT_SHA}"}]}}}}
          EOF
        env:
          REGISTRY_URL: "registry.home:30500"
