name: Deploy to local cluster
on:
  pull_request_target:
    types:
      - closed
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: home-arc-runners
    container:
      image: bitnami/kubectl@sha256:f737259db1fb8d90b18bcacd6233291ce22c31ac452ca71dc7aad48e90f85ac1

    steps:
      - name: Patch deployment with new image
        run: |
          kubectl patch deployment dicebox-app-deployment --namespace www --patch-file=/dev/stdin <<-EOF
          { "spec": { "template": { "spec": { "containers": [ { "name": "app", "image": "$REGISTRY_URL/${{ github.repository }}:$(echo ${GITHUB_SHA} | head -c 7)"}]}}}}
          EOF
        env:
          REGISTRY_URL: "registry.home:30500"